### ISSUE TITLE
Awesome Twitter Bots

### ISSUE THREAD

**Issue by spences10** [FiF0o/twitterapp#1]
Hey there, 

Nice bot 👌, mind if I add it to our [Awesome Twitter Bots Repo][awesome]?

[awesome]: https://github.com/amandeepmittal/awesome-twitter-bots

**Comment by FiF0o** [comment]
Hey @spences10,
Nice to hear, thank you!
Sure no problem with that 👍

**Comment by spences10** [comment]
[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

https://github.com/amandeepmittal/awesome-twitter-bots
